version: '3.1'
services:
  stat-server:
    build: ./stats/stats-server
    image: stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_HOST=stats-db
        DB_PORT=5432

  stats-db:
    image: postgres:14.6
    container_name: statsDb
    restart: always
    volumes:
      - /var/lib/postgresql/data1
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ./explore-main
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - stat-server
      - ewm-db
    environment:
      - application.name=explore-main
      - stat-server.url=http://stat-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://emw-db:5432/emw-db
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - DB_NAME=emw-db
      - DB_HOST=emw-db
        DB_PORT=5432

  ewm-db:
    image: postgres:14.6
    container_name: emw-db
    restart: always
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=emw-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres