version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    image: stat-server
    container_name: stat-server-cont
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsDb
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root
      - DB_NAME=statsDb
      - DB_HOST=stats-db
        DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: statsDb
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsDb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./explore-main
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - application.name=explore-main
      - stat-server.url=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/emwDb
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root
      - DB_NAME=emwDb
      - DB_HOST=db
        DB_PORT=5444

  ewm-db:
    image: postgres:14-alpine
    container_name: emwDb
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=emwDb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root